# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90cca45030a9c00d9ea0765b1e3738c4e7eabfe85023b49ecac7ef83330a56a3315022426010112f486724847ce75bcddb44538d3c03d94d6f0eb30561500ba3

test:
  secret_key_base: 31edd07545f4042748d943ac988f71c6a35952c117e83ad2242b04b17fc75cda3d9f4ebe3df97b44db20743fb734f3e0e11094b16dca7dc98853b27ffb4b112c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
